version: "3.9"
services:
  api:
    build: ./apps/api
    ports: ["8000:8000"]
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./models:/root/.cache
    deploy:
      resources:
        reservations:
          devices: [{ capabilities: ["gpu"] }]
    depends_on: [redis]

  worker:
    build: ./apps/worker
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./models:/root/.cache
    deploy:
      resources:
        reservations:
          devices: [{ capabilities: ["gpu"] }]
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
